name: Acquire Unity activation file
on:
  workflow_dispatch: {}
jobs:
  activation:
    runs-on: ubuntu-latest
    steps:
      - name: Request manual activation file
        uses: game-ci/unity-request-activation-file@v2
        id: getManualLicenseFile
        with:
          unityVersion: 6000.0.53f1 # Change to your Unity version

      - name: Upload activation file
        uses: actions/upload-artifact@v3
        with:
          name: Manual-Activation-File
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
